### ISSUE TITLE
two passenger installs

### ISSUE THREAD

**Issue by robertgarrigos** [Platoniq/decidim-install#2]
Following directions to install on ubuntu 18.04 I'm getting this message when validating passenger install, which is not the expected:

```
passenger-config validate-install
What would you like to validate?
Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Passenger itself
   ⬡  Apache

-------------------------------------------------------------------------

 * Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... (!)

   You are currently validating against Phusion Passenger 5.3.3, located in:
   
     /usr/bin/passenger
   
   Besides this Passenger installation, the following other
   Passenger installations have also been detected:
   
     /home/decidim/.rbenv/versions/2.5.1/bin/passenger
   
   Please uninstall these other Passenger installations to avoid
   confusion or conflicts.


Detected 0 error(s), 1 warning(s).
```

**Comment by microstudi** [comment]
That's because the gem introduced into Decidim installs that extra passenger binary. However In the manual we are using the one coming from the repositories. As far as I know, it's not a problem.
The configuration for which passenger version are we using are in thiese files:
```
more /etc/nginx/conf.d/mod-http-passenger.conf
/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
```

**Comment by robertgarrigos** [comment]
I actually followed your manual, though.

**Comment by psaunders** [comment]
Can confim that as of this AM if you follow the guide you will end up with this error and have to edit ```mod-http-passenger.conf```

**Comment by Digharatta** [comment]
@psaunders As of today, this in included in the guide, so I've got  no errors.

**Comment by robertgarrigos** [comment]
Better mark this as fixed, then. Feel free top open it if you encounter with this error again.

**Comment by stephanedesjardins-qc** [comment]
Good morning,
I did follow the guide for manual installation. Did on an AWS EC2 Ubuntu instance.  Had the same error, two passenger installed, did modify to point to: passenger_ruby /home/decidim/.rbenv/shims/ruby;

And edit the decidim.conf file as supposed with the DNS of the EC2 instance... 

server {
    listen 80;
    listen [::]:80 ipv6only=on;

    server_name ec2-Instance-IP.compute-1.amazonaws.com;
    client_max_body_size 32M;

    passenger_enabled on;
    passenger_ruby /home/decidim/.rbenv/shims/ruby;

    rails_env    production;
    root         /home/decidim/decidim-app/public;
}

an have 404 error

**Comment by rannyeribatista** [comment]
In your case, you have installed the /home/decidim/.rbenv/versions/2.5.1/bin/passenger by using rbenv. You can execute the uninstall of this second version by running "gem uninstall passenger". This also works for rvm btw, this is what my environment looked like:

```
* Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... (!)

   You are currently validating against Phusion Passenger(R) 6.0.18, located in:
   
     /usr/bin/passenger
   
   Besides this Passenger installation, the following other
   Passenger installations have also been detected:
   
     /usr/local/rvm/gems/ruby-2.7.3/bin/passenger
   
   Please uninstall these other Passenger installations to avoid
   confusion or conflicts.
```

and after executing the gem uninstall I get this:
```
Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... ✓

Everything looks good. :-)
```

problem solved!
