### ISSUE TITLE
keep redirecting to /system/admins/sign_in

### ISSUE THREAD

**Issue by adamito** [Platoniq/decidim-install#24]
Hello

Thank you for your install guide.

I managed to install finish the install, I was able to create an organization and I received a invitation link : 

/users/invitation/accept?invitation_token=H7VzMko7A22Z3_YJRPeU&invite_redirect=%2Fadmin%2F

But I try to open it, I'm always redirected to : 

 /system/admins/sign_in

Can you please help me ?

**Comment by microstudi** [comment]
Hi, are you using SSL?
can you post the last lines (where the error appears at least) of the `log/produciton.log`?

**Comment by adamito** [comment]
Thank your for the answer.

Yes I'm using SSL and it works well (I can create admins and organizations only)

There is no error, but just a redirect.

I, [2019-03-20T13:27:36.398212 #31945]  INFO -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a] Started GET "/users/invitation/accept?invitation_token=apPCXyQN4tEsdeahq28U&invite_redirect=%2Fadmin%2F" for 105.154.64.178 at 2019-03-20 13:27:36 +0100
D, [2019-03-20T13:27:36.399348 #31945] DEBUG -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a]   Decidim::Organization Load (0.3ms)  SELECT  "decidim_organizations".* FROM "decidim_organizations" WHERE "decidim_organizations"."host" = $1 LIMIT $2  [["host", "demo.adambouhadma.com"], ["LIMIT", 1]]
D, [2019-03-20T13:27:36.400447 #31945] DEBUG -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a]   Decidim::Organization Load (0.5ms)  SELECT  "decidim_organizations".* FROM "decidim_organizations" WHERE ('demo.adambouhadma.com' = ANY(secondary_hosts)) LIMIT $1  [["LIMIT", 1]]
I, [2019-03-20T13:27:36.402497 #31945]  INFO -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a] Processing by Decidim::Devise::InvitationsController#edit as HTML
I, [2019-03-20T13:27:36.402537 #31945]  INFO -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a]   Parameters: {"invitation_token"=>"apPCXyQN4tEsdeahq28U", "invite_redirect"=>"/admin/"}
D, [2019-03-20T13:27:36.404142 #31945] DEBUG -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a]   Decidim::User Load (0.6ms)  SELECT  "decidim_users".* FROM "decidim_users" WHERE "decidim_users"."type" IN ('Decidim::User') AND "decidim_users"."invitation_token" = $1 ORDER BY "decidim_users"."id" ASC LIMIT $2  [["invitation_token", "d6e20a6abf1b9b20975cc97b7560d0b1f37424879d7a1a49df4c44d3d8bd22de"], ["LIMIT", 1]]
I, [2019-03-20T13:27:36.405233 #31945]  INFO -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a] Redirected to http://demo.adambouhadma.com/system/
I, [2019-03-20T13:27:36.405311 #31945]  INFO -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a] Filter chain halted as :verify_organization rendered or redirected
I, [2019-03-20T13:27:36.405400 #31945]  INFO -- : [0f928e05-07cd-427d-a4a7-12f0e6c2532a] Completed 302 Found in 3ms (ActiveRecord: 0.6ms)
I, [2019-03-20T13:27:36.478616 #31945]  INFO -- : [527d4489-1b5e-4e33-b7de-dbe7c3353288] Started GET "/system/" for 105.154.64.178 at 2019-03-20 13:27:36 +0100
D, [2019-03-20T13:27:36.479593 #31945] DEBUG -- : [527d4489-1b5e-4e33-b7de-dbe7c3353288]   Decidim::Organization Load (0.3ms)  SELECT  "decidim_organizations".* FROM "decidim_organizations" WHERE "decidim_organizations"."host" = $1 LIMIT $2  [["host", "demo.adambouhadma.com"], ["LIMIT", 1]]
D, [2019-03-20T13:27:36.480469 #31945] DEBUG -- : [527d4489-1b5e-4e33-b7de-dbe7c3353288]   Decidim::Organization Load (0.2ms)  SELECT  "decidim_organizations".* FROM "decidim_organizations" WHERE ('demo.adambouhadma.com' = ANY(secondary_hosts)) LIMIT $1  [["LIMIT", 1]]
D, [2019-03-20T13:27:36.483122 #31945] DEBUG -- : [527d4489-1b5e-4e33-b7de-dbe7c3353288]   Decidim::System::Admin Load (0.4ms)  SELECT  "decidim_system_admins".* FROM "decidim_system_admins" WHERE "decidim_system_admins"."id" = $1 ORDER BY "decidim_system_admins"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
I, [2019-03-20T13:27:36.586659 #31945]  INFO -- : [527d4489-1b5e-4e33-b7de-dbe7c3353288] Processing by Decidim::System::DashboardController#show as HTML
I, [2019-03-20T13:27:36.603639 #31945]  INFO -- : [527d4489-1b5e-4e33-b7de-dbe7c3353288]   Rendering /home/decidim/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/decidim-system-0.16.0/app/views/decidim/system/dashboard/show.html.erb within layouts/decidim/system/application

**Comment by adamito** [comment]
I just found that I didn't put the subdomain as host for my organization.

I taught I had to put the address with https ...

Thank you
