### ISSUE TITLE
Can't deploy decidim due to charlock_holmes / icu4c issue

### ISSUE THREAD

**Issue by FPoezevara** [Platoniq/decidim-install#25]
Hi, 

I am trying to install Decidim on AWS EC2, following this tutorial: https://github.com/Platoniq/decidim-install/blob/master/decidim-aws.md

The first issue I encounter is at this step: 
`eb create production`
It is said in the tuto that the command should fail due to environment variables not set, but I'm pretty sure that the error I get is not the one supposed to happen. 

> 2019-04-06 11:39:39    ERROR   [Instance: i-0af6dc61fc01eb0eb] Command failed on instance. Return code: 5 Output: (TRUNCATED)...esolved to 0.17.0, which depends on
>     decidim-accountability was resolved to 0.17.0, which depends on
>       decidim-comments was resolved to 0.17.0, which depends on
>         decidim-core was resolved to 0.17.0, which depends on
>           charlock_holmes. 
> Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/10_bundle_install.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
> 2019-04-06 11:39:39    INFO    Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].

I tried to go further anyway, but when deploying my app:
`eb deploy`
The same issue happens:

> 019-04-06 11:59:50    ERROR   [Instance: i-0af6dc61fc01eb0eb] Command failed on instance. Return code: 5 Output: (TRUNCATED)...esolved to 0.17.0, which depends on
>     decidim-accountability was resolved to 0.17.0, which depends on
>       decidim-comments was resolved to 0.17.0, which depends on
>         decidim-core was resolved to 0.17.0, which depends on
>           charlock_holmes. 
> Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/10_bundle_install.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
> 2019-04-06 11:59:50    INFO    Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].

And I get a nice 
> ERROR: ServiceError - Failed to deploy application

When I look into the log, I see this:

>   ***************************************************************************************
>   *********** icu required (brew install icu4c or apt-get install libicu-dev)
>   ***********
>   ***************************************************************************************
>   *** extconf.rb failed ***
>   Could not create Makefile due to some reason, probably lack of necessary
>   libraries and/or headers.  Check the mkmf.log file for more details.  
And

> An error occurred while installing charlock_holmes (0.7.6), and Bundler cannot
>   continue.
>   Make sure that `gem install charlock_holmes -v '0.7.6' --source
>   'https://rubygems.org/'` succeeds before bundling.
>   
>   In Gemfile:
>     decidim was resolved to 0.17.0, which depends on
>       decidim-accountability was resolved to 0.17.0, which depends on
>         decidim-comments was resolved to 0.17.0, which depends on
>           decidim-core was resolved to 0.17.0, which depends on
>             charlock_holmes (Executor::NonZeroExitStatus)

I looked over Internet and it seems that others had a similar problems, caused by incompatibility between icu4c and charlock_holmes versions. 
Here are my versions:
icu4c: stable 63.1
charlock_holmes (0.7.6)

Do you know if the issue I encounter has anything to do with this? And how I could solve it plz?

Thanks,
Best regards

**Comment by microstudi** [comment]
Hi, i think a new dependency since I made the tutorial shown up.

Please try to create this file : `.ebextensions/00_packages.config` with this content:
```yaml
packages:
  yum:
    git: []
    libicu-devel: []
```
Then commit and deploy again.
See if this error goes away, if that's the case I'll update the guide.

**Comment by FPoezevara** [comment]
Yes it works perfectly! Thanks a lot :)
