### ISSUE TITLE
Getting charged for Redis use

### ISSUE THREAD

**Issue by FPoezevara** [Platoniq/decidim-install#27]
Hi,

I deployed decidim on AWS following this guide :
https://github.com/Platoniq/decidim-install/blob/master/decidim-aws.md

Everything is working (except Twitter login, but I didn't investigate), but there is the problem with the Redis use. I am being charged by Amazon, because the T2 Micro Cache node-hour (or partial hour) running Redis under monthly Free Tier is limited to 750 hours and I used 879 extra hours... 

Do you know why? How can I avoid being charged please?

Thank you,
Best regards.

**Comment by microstudi** [comment]
You probably have activated Multi A-Z availability. This creates a secondary server for backup and availability but it's not included in the Free Tier. Check in your ElasticCache Managment page for an option like this:
![image](https://user-images.githubusercontent.com/1401520/57224138-b9288300-7008-11e9-903f-3a43149833f2.png)

**Comment by FPoezevara** [comment]
Hi,

Thank you for your answer. Multi-AZ is actually disabled, but I have 3 nodes :
![image](https://user-images.githubusercontent.com/49340385/57225763-964c9d80-700d-11e9-9c5f-95a3662a3927.png)
I think this is why I am getting charged ? Do I need to manually delete the 2nd et 3rd nodes?
![image](https://user-images.githubusercontent.com/49340385/57225814-bbd9a700-700d-11e9-995e-73d4a3245de6.png)
Thanks!

**Comment by microstudi** [comment]
Not sure, please follow the official recommendations:
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.html

**Comment by ismaelben** [comment]
@FPoezevara I had the same problem, it's when creating redis, you have to be careful to put the node t2-micro and number of replica: 0. By default the node is R4.large which is very expensive and replica : 3

**Comment by FPoezevara** [comment]
Hi,
Actually I asked aws support, and all you need to do is to delete the replicas. No need to recreate the node ;)
