### ISSUE TITLE
Missing step: libicu-dev

### ISSUE THREAD

**Issue by teusbenschop** [Platoniq/decidim-install#31]
```gem install decidim```
This fails to install decidim

``cat /home/decidim/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/charlock_holmes-0.7.6/mkmf.log``

It appears that it needs libicu.
The fix is this: ```sudo apt install libicu-dev```

Should this be mentioned in the installation instruction?

By the way, thank you for the great installation instructions, they were so helpful!

**Comment by microstudi** [comment]
Yes, I think is required since version 0.17 of Decidim. It was also commented in https://github.com/Platoniq/decidim-install/issues/25. I'll update the guide, thanks for the heads up.

**Comment by microstudi** [comment]
Updated in the guide now
