### ISSUE TITLE
Error with  gem charlock_holmes on Install with ElasticBeanstalk

### ISSUE THREAD

**Issue by ismaelben** [Platoniq/decidim-install#33]
HI, when I do the step 5, `eb deploy` I get :
> An error occurred while installing charlock_holmes (0.7.6), and Bundler cannot
continue.
Make sure that `gem install charlock_holmes -v '0.7.6' --source
'https://rubygems.org/'` succeeds before bundling.

> In Gemfile:
> decidim was resolved to 0.17.1, which depends on
> decidim-accountability was resolved to 0.17.1, which depends on
> decidim-comments was resolved to 0.17.1, which depends on
> decidim-core was resolved to 0.17.1, which depends on
> charlock_holmes.

Do you know how to solve this? I could not find, so I am trying another solution with heroku, but maybe I am not the only one to had this problem.

**Comment by microstudi** [comment]
Since version 01.7 the package libicu-dev is needed.
Check this for this for the solution:
https://github.com/Platoniq/decidim-install/issues/25

I'll update the guide to incorpore this soon

**Comment by microstudi** [comment]
Updated in the guide now.
