### ISSUE TITLE
Cannot deploy initiatives and consultations modules in Amazon AWS

### ISSUE THREAD

**Issue by anggilb** [Platoniq/decidim-install#49]
Howdy to everyone, this issue is very similar to the #40, but one step later...

For my part, I followed the [AWS Elastic Beanstalk tutorial](https://github.com/Platoniq/decidim-install/blob/master/decidim-aws.md) (very very good) and not problem, I got the expected result. 

In this point I decided to advance more testing the initiatives and consultations modules uncommenting the gems in the Gemfile. At the beginning I found some problems as the wicked_pdf of the issue #40 that I fixed fine, I can test the modules in my local.

Afterwards I decided to publish this in AWS server, but at this moment I can´t achieve this: at the beginning I found disk space errors that I resolve increasing the volume capacity from 8GB to 16GB and the error disappeared. But now the problem are the timeouts: the deploy have a duration of more that 10 minutes and always I get the timeout, even changing this parameter for configuration.

When I execute the next commands for update in local the gems, the await it is very large too but at the final it works fine. I suppose that it is a problem with the dependencies of the uncomment modules, because when I execute this same commands with this lines uncomment, I haven´t this problem of latency.

```
bundle update
bin/rails decidim:upgrade
```

How can I do to fix this error?

Thanks in advance.

**Comment by microstudi** [comment]
Hi @anggilb thanks for you report.
I am not sure of what your problem is, is just that the publication takes a long time but afterwards it works? or is it that it never gets published?
Can you post the error log from the ElasticBeanstalk console? when a publication fails it shows the details in the "health" page.

**Comment by anggilb** [comment]
In the events log appear the next info when I have a timeout:

```2020-04-29 01:56:31    INFO    Environment update is starting.
2020-04-29 01:56:35    INFO    Deploying new version to instance(s).
2020-04-29 02:17:17    WARN    The following instances have not responded in the allowed command timeout time (they might still finish eventually on their own): [i-08c1507290145c4d0].
2020-04-29 02:17:17    INFO    Command execution completed on all instances. Summary: [Successful: 0, TimedOut: 1].
2020-04-29 02:17:17    ERROR   Unsuccessful command execution on instance id(s) 'i-08c1507290145c4d0'. Aborting the operation.
2020-04-29 02:17:17    ERROR   Failed to deploy application.
2020-04-29 02:17:17    ERROR   During an aborted deployment, some instances may have deployed the new application version. To ensure all instances are running the same version, re-deploy the appropriate application version.
```

I opened the /var/log/healthd/daemon.log file, but there are no ERRORs, only some warnings as this /var/log/nginx/healthd/application.log.2020-04-29-09" does not exist.

Finally I looked in another folders as Puma (I tested to with Passenger without success) and Nginx but there are not errors.

Now I am testing a execution with long timeout and it is working for 1,5 hours, I am waiting for the final result.

**Comment by anggilb** [comment]
I started the execution at 10.08 and finished at 12:59 with timeout again, this is the Health details in AWS Elastic Beanstalk production state -> "Health details":

```Performing application update (running for 12 hours).
Incorrect application version "app-2187-200429_004341" (deployment 15). Expected version "app-2187-200429_004341" (deployment 15).
Instance ELB health state has been "OutOfService" for 11 hours: Instance has failed at least the UnhealthyThreshold number of health checks consecutively.
Following services are not running: proxy.
```

What do you think?

**Comment by microstudi** [comment]
You extract more meaningful errors by login into the machine and view the error "realtime", these would be the commands:
```
eb ssh
tail /var/log/eb-activity.log -f
```

BTW, it may be this, can you check which version of sidekiq are you using?
```
grep sidekiq Gemfile.lock
```

It may be that you are running version 6 and the guide uses version 5. If that is the case, please add this to the Gemfile:
```
gem "sidekiq", "~> 5.2"
gem "sidekiq-cron"
```

bundle and try again.

**Comment by anggilb** [comment]
I returned to reproduce the issue, there another question that can be related:

When I execute "bundle update", it appear an error related with the bundler version:

```
2020-04-29 22:11:50    ERROR   [Instance: i-0b94ca585ffda1361] Command failed on instance. Return code: 1 Output: (TRUNCATED)...your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.2`
	from /opt/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	from /opt/rubies/ruby-2.6.5/bin/bundle:23:in `<main>'. 
Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/10_bundle_install.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
```

For resolve it I follow a comment of a forum ho saids delete this 2 lines in Gemfile.lock and try again:

```
BUNDLED WITH
   2.1.4
````

This is in all the cases. I suppose that it can be related.

Without the initiatives and consultations modules I can use the platform in AWS, with this modules I have problems to update and deploy.

About "sidekiq" originally I didn´t use this (not appear in Gemfile.lock), but I tested to follow the chapter of the AWS instalation guide and not success neither.

Finally I copy and paste the log eb-activity.log:

````
[2020-04-30T00:29:48.763Z] INFO  [32684] - [Application update app-fdf5-200430_022834@10/AppDeployStage0/AppDeployPreHook/10_bundle_install.sh] : **Activity execution failed, because: ++ /opt/elasticbeanstalk/bin/get-config container -k script_dir**
  + EB_SCRIPT_DIR=/opt/elasticbeanstalk/support/scripts
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_staging_dir
  + EB_APP_STAGING_DIR=/var/app/ondeck
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_user
  + EB_APP_USER=webapp
  ++ /opt/elasticbeanstalk/bin/get-config container -k support_dir
  + EB_SUPPORT_DIR=/opt/elasticbeanstalk/support
  + . /opt/elasticbeanstalk/support/envvars-wrapper.sh
  +++ /opt/elasticbeanstalk/bin/get-config container -k support_dir
  ++ EB_SUPPORT_DIR=/opt/elasticbeanstalk/support
  ++ set +x
  + . /opt/elasticbeanstalk/support/scripts/use-app-ruby.sh
  ++ . /usr/local/share/chruby/chruby.sh
 +++ CHRUBY_VERSION=0.3.9
  +++ RUBIES=()
  +++ for dir in '"$PREFIX/opt/rubies"' '"$HOME/.rubies"'
  +++ [[ -d /opt/rubies ]]
  ++++ ls -A /opt/rubies
  +++ [[ -n ruby-1.9.3-p551
  ruby-2.0.0-p648
  ruby-2.1.10
  ruby-2.2.10
  ruby-2.3.8
  ruby-2.4.9
  ruby-2.5.7
  ruby-2.6.5
  ruby-current ]]
  +++ RUBIES+=("$dir"/*)
  +++ for dir in '"$PREFIX/opt/rubies"' '"$HOME/.rubies"'
  +++ [[ -d /.rubies ]]
  +++ unset dir
  +++ cat /etc/elasticbeanstalk/.ruby_version
++ chruby 2.6.5
  ++ case "$1" in
  ++ local dir match
  ++ for dir in '"${RUBIES[@]}"'
  ++ dir=/opt/rubies/ruby-1.9.3-p551
  ++ case "${dir##*/}" in
  ++ for dir in '"${RUBIES[@]}"'
  ++ dir=/opt/rubies/ruby-2.0.0-p648
  ++ case "${dir##*/}" in
  ++ for dir in '"${RUBIES[@]}"'
  ++ dir=/opt/rubies/ruby-2.1.10
  ++ case "${dir##*/}" in
  ++ for dir in '"${RUBIES[@]}"'
  ++ dir=/opt/rubies/ruby-2.2.10
  ++ case "${dir##*/}" in
  ++ for dir in '"${RUBIES[@]}"'
  ++ dir=/opt/rubies/ruby-2.3.8
  ++ case "${dir##*/}" in
  ++ for dir in '"${RUBIES[@]}"'
  ++ dir=/opt/rubies/ruby-2.4.9
  ++ case "${dir##*/}" in
  ++ for dir in '"${RUBIES[@]}"'
  ++ dir=/opt/rubies/ruby-2.5.7
  ++ case "${dir##*/}" in
  +
````

But it is not a clue for me...

**Comment by microstudi** [comment]
This is because AWS uses 1.7.3 version of bundler, you need to create your Gemfile.lock using that version, install it and force that specific version in your sistem it (subsequents uses of the command `bundle` won't need the version anymore):

```
gem install bundler:1.17.3
rm Gemfile.lock
bundle _1.17.3_ install
```

**Comment by anggilb** [comment]
Finally was this, very very thanks for all @microstudi. I am testing with this application in AWS and all is fine.

**Comment by microstudi** [comment]
Feel free to make a pull request if you want!
