### ISSUE TITLE
Install not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by AnthonyFon** [Platoniq/decidim-install#67]
Hi,

Firstly, sorry for my poor english.
I'm trying for to install Decedim on a VPS with a clean install with Ubuntu 18.04. I try 4 times, never work for me :(
I read and do all the things which are on the guide (thanks a lot for this one!).
All is OK before install Passenger (I see the welcome nginx page if I'm going on http://mydomain).
Then I install passenger, and after that I can't see anything when I go on http://mydomain, only a blank page with error. If I go on http://mydomain that always redirect to https://mydomain and nothing happen.

My config : 

/etc/nginx/conf.d/mod-http-passenger.conf

### Begin automatically installed Phusion Passenger config snippet ###
passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby /home/decidim/.rbenv/shims/ruby;
#passenger_ruby /home/decidim/.rbenv/versions/2.6.3/bin/ruby;
### End automatically installed Phusion Passenger config snippet ###

/etc/nginx/sites-enabled/decidim.conf

server {
    listen 80;
    listen [::]:80 ipv6only=on;

    server_name nextcloud.soyaux.cloud;
    client_max_body_size 32M;

    passenger_enabled on;
    passenger_ruby /home/decidim/.rbenv/shims/ruby;

    rails_env    production;
    root         /home/decidim/decidim-app/public;
}

Please, help me :)
Best regards,
Antho.

**Comment by BigSnicker** [comment]
One of the issues is that the latest versions of decidim force ssl, but the
install script doesn't configure ssl.

So you can either install ssl with certbot, or we had success doing the
following:

Go to /decidim-app/config/initializers/decidim.rb

and set

config.force_ssl = false

**Comment by AnthonyFon** [comment]
Thank's a lot !
I have install ssl with certbot, everything seems to work !
I always try to make it working without ssl, that why I don't try to install ssl. 

Thank you  @BigSnicker

**Comment by microstudi** [comment]
Yes, this decidim by the core team of Decidim to force SSL by default may lead to this kind of issues.
Do you think that would be a good idea for the script to disabled SSL by default and warn the user to configure it manually?

**Comment by BigSnicker** [comment]
> Do you think that would be a good idea for the script to disabled SSL by
default and warn the user to configure it manually?

Very much so, and recommend using snap packages for installations on 20.04
or later.

**Comment by AnthonyFon** [comment]
Hi, 
That could be a good idea to warn the user, because I try the script and have the same problem, so I try manually, and same problem. In the guide, it could be interesting to explain that we have to use certbot if we want to have a working Decidim.

**Comment by microstudi** [comment]
ok, labeled as a "bug" so I'll fixi it as soon as i can

**Comment by microstudi** [comment]
Happy to announce that I've modifed the script. updated for ubuntu 20.04 and removing the ssl by default. Also added a github action to test it!
