### ISSUE TITLE
Site not found (404) 

### ISSUE THREAD

**Issue by andreslucena** [Platoniq/decidim-install#86]
Seems like the GitHub pages deployment is broken: https://platoniq.github.io/decidim-install/ 

I get a 404:

> There isn't a GitHub Pages site here.

**Comment by bkmgit** [comment]
@microstudi @andreslucena  It seems that GitHub pages is not enabled or is enabled for an incorrect branch/folder. By enabling GitHub pages on the main branch for the root folder, could view site contents at https://bkmgit.github.io/decidim-install/

**Comment by microstudi** [comment]
Thanks @bkmgit !!
It should be working now!

**Comment by bkmgit** [comment]
@microstudi Thanks.
